services:
  inventario:
    build:
      context: .
      # Usamos el Dockerfile principal (desarrollo) o puedes cambiarlo a Dockerfile.prod para producción
      dockerfile: Dockerfile
    image: inventario
    container_name: inventario
    restart: always
    ports:
      # Mapeamos el puerto 4330 de la máquina anfitriona al puerto 8000 del contenedor
      - "4330:8000"