services:
  inventario:
    build:
      context: .
      # Usamos el Dockerfile principal (desarrollo) o puedes cambiarlo a Dockerfile.prod para producción
      dockerfile: Dockerfile
    image: inventario
    container_name: inventario
    restart: always
    ports:
      # Mapeamos el puerto 4200 de la máquina anfitriona al puerto 4200 del contenedor
      - "4200:4200"