server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy opcional si quieres que el front hable con el back 
    # usando una ruta relativa como /api/
    #location /api/ {
    #    proxy_pass http://api:9090/;
    #}
}
